# Generated by Django 4.1 on 2023-10-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_student_id_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('complete', 'Complete')], default='in progress', max_length=20),
        ),
    ]
