# Generated by Django 4.1 on 2023-10-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('조리중', '조리중'), ('조리 완료', '조리 완료')], default='조리중', max_length=20),
        ),
    ]
